### ISSUE TITLE
Invalid parsing of MSI scope

### ISSUE THREAD

**Issue by jjcollinge** [deislabs/cnab-azure-driver#28]
When supplying a `CNAB_AZURE_SYSTEM_MSI_SCOPE` it is [parsed](https://github.com/deislabs/cnab-azure-driver/blob/aeb746fa1b9000d1b2e44b48a3823c1992baeede/pkg/driver/aci-driver.go#L224) against the [Azure resource id regex](https://github.com/Azure/go-autorest/blob/c7f947c0610de1bc279f76e6d453353f95cd1bfa/autorest/azure/azure.go#L217) which errors on valid scopes. The autorest parser expects a fully formed resource id (`(?i)subscriptions/(.+)/resourceGroups/(.+)/providers/(.+?)/(.+?)/(.+)`). However, MSI scopes can be defined by prefixes such as `/subscriptions/(.+)` or `/subscriptions/(.+)/resourceGroups/(.+)` which fail this regex match.
In fact, if you leave `CNAB_AZURE_SYSTEM_MSI_SCOPE`  empty the scope is [set by the driver](https://github.com/deislabs/cnab-azure-driver/blob/aeb746fa1b9000d1b2e44b48a3823c1992baeede/pkg/driver/aci-driver.go#L851) to `fmt.Sprintf("/subscriptions/%s/resourcegroups/%s", d.subscriptionID, d.aciRG)` - but you can't actually supply this value as the scope via the command line as it will fail parsing.
![bug](https://user-images.githubusercontent.com/7241190/121160249-d3666800-c843-11eb-9e2f-1b47870404bc.png)

If we agree this is a bug, I'll look to fix it when I find time.

Offending line: https://github.com/deislabs/cnab-azure-driver/blob/aeb746fa1b9000d1b2e44b48a3823c1992baeede/pkg/driver/aci-driver.go#L224

**Comment by simongdavies** [comment]
@jjcollinge yes please fix if you have time
