### ISSUE TITLE
Test credentials need to be refreshed

### ISSUE THREAD

**Issue by carolynvs** [deislabs/cnab-azure-driver#80]
The test credentials used for running the CI tests have expired and need to be refreshed and then the CI secrets updated.

https://dev.azure.com/deislabs/cnab-azure-driver/_build/results?buildId=7157&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86

**Comment by simongdavies** [comment]
Fixed.
